### ISSUE TITLE
I want to try to help

### ISSUE THREAD

**Issue by masalyuk** [tusharhero/aitelegrambot#2]
Hello! I'm newbie in LLM world and telegram bot but I'm wondering to investigate this areas.  

I'm @masalyuk in telegram and Discord.

**Comment by tusharhero** [comment]
Hey @masalyuk, I don't have an account on telegram or discord. We can communicate via email if you want it to be private: tusharhero@sdf.org

**Comment by masalyuk** [comment]
@tusharhero, actually, I could go on and on here. But in any case, I will write to you by email to keep in touch

**Comment by tusharhero** [comment]
Hey, @masalyuk If that is the case, I think it would be better to continue this discussion here.

**Comment by tusharhero** [comment]
@masalyuk you can try #3.

**Comment by masalyuk** [comment]
@tusharhero I'll try thank you
